### ISSUE TITLE
Questions for Alzheimers_DNAm paper

### ISSUE THREAD

**Issue by weizhousjtu** [LieberInstitute/Alzheimers_DNAm#1]
Thank you for upload the code of the article “Integrated DNA methylation and gene expression profiling across multiple brain regions implicate novel genes in Alzheimer’s disease”. It really helps a lot!

However, I could not find the function “dmrPlot” in “03b_caseControl_DMR_plots.R” . Could you help me? I am looking forward to hear from you.

**Comment by SteveSemick** [comment]
Hi,

Thank you for your interest. I've added "_00_Alz_DNAm_methylation_functions.R_" which has the dmrPlot function. This is a modification, for hg38 compatibility, of code from "00_devMeth450k_functions.R" in https://github.com/andrewejaffe/devMeth450k.

Best,
Steve
